on:
  rss:
    url: https://hnrss.org/newest?points=300&count=3
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.rss.outputs.title}}
          contentSnippet: ${{on.rss.outputs.contentSnippet}}
          link: ${{on.rss.outputs.link}}
        run: |
          echo title: $title
          echo contentSnippet: $contentSnippet
          echo link: $link
      - id: step1
        name: Test Step
        run: echo "::set-output name=test::hello"
      - name: Make a HTTP Request
        uses: actionsflow/axios@v1
        with:
          url: https://hookb.in/VGqBpdYE3PFDrgoor0Xp
          method: POST
          body: |
            {
              "link":"${{ on.rss.outputs.link }}", 
              "title": "${{ on.rss.outputs.title }}",
              "content":"<<<${{ on.rss.outputs.contentSnippet }}>>>"
            }
