on:
  rss:
    url: https://hnrss.org/newest?points=50&count=3
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs 2
        env:
          outputs: ${{ toJSON(on.rss.outputs) }}
        run: |
          echo outputs: $outputs
      - name: Print Outputs
        env:
          title: ${{on.rss.outputs.title}}
          contentSnippet: ${{on.rss.outputs.contentSnippet}}
          link: ${{on.rss.outputs.link}}
        run: |
          echo title: $title
          echo contentSnippet: $contentSnippet
          echo link: $link
      - id: step1
        name: Test Step
        run: echo "::set-output name=test::hello"
      - name: Make a HTTP Request
        uses: actionsflow/axios@v1
        with:
          url: https://hookb.in/E70VnWPljDsVjY66jOdB
          method: POST
          body: |
            {
              "link":"${{ on.rss.outputs.link }}", 
              "title": "${{ on.rss.outputs.title }}",
              "content":"<<<${{ on.rss.outputs.contentSnippet }}>>>"
            }
      - name: Slack notification
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}          
        uses: Ilshidur/action-slack@2.0.2
        with:
          args: 'New Content found: ${{on.rss.outputs.title}} / ${{on.rss.outputs.link}}'
